ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from store import views as user_views

from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from store import views as app_views
from authentication import views as user_views
from payment import views as payment_views
from cart import views as cart_views
from product import views as product_views
from review import views as review_views

from django.urls import include, path
from rest_framework import routers
from api.views import ProductView, PlaceOrders

router = routers.DefaultRouter()
router.register('products', ProductView)
router.register('orders', PlaceOrders)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.home, name='home'),
    path('profile/', user_views.profile, name='profile'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('change-password/', user_views.change_password, name='change-password'),
    path('edit-profile/', user_views.edit_profile, name='edit-profile'),

    path('products/', product_views.product_list, name='product_list'),

    path('cart/', cart_views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/',
         cart_views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/',
         cart_views.remove_from_cart, name='remove_from_cart'),


    path('checkout/', payment_views.checkout, name='checkout'),

    path('submit_review/<int:product_id>/',
         review_views.submit_review, name='submit_review'),
    path('product_detail/<int:product_id>/',
         review_views.product_detail, name='product_detail'),


    path('api/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
]

cart/models.py
from django.contrib.auth.models import User
from django.db import models
from product.models import Product


class Cart(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

product/models.py
from django.contrib.auth.models import User
from django.db import models
import os


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to=os.path.join(os.path.dirname(
        __file__)[:-8], 'store', 'static', 'product_images'))
    stock = models.PositiveIntegerField()

    def __str__(self):
        return self.name

product/views.py
from django.contrib.auth import update_session_auth_hash
from PIL import Image
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.conf import settings
from django.urls import reverse

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from .models import Product
import os


def product_list(request):
    products = Product.objects.all()

    paginator = Paginator(products, 2)

    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    context = {
        'products': products,
        'page': page
    }
    return render(request, 'product_list.html', context)

product/templates/product_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>E-commerce Hub</title>

    <link
      href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    {% load static %}
    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all" />
    <link href="{% static 'css/post.css' %}" rel="stylesheet" media="all" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <script
      src="https://kit.fontawesome.com/700b873bbf.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body>
    <header>
      <h4>
        <a href="{% url 'home' %}">E-commerce Hub</a>
      </h4>
      <nav>
        {% if user.is_authenticated %}
        <li><a href="{% url 'home' %}">Home</a></li>
        <li>
          <a href="{% url 'cart' %}"
            >Cart ({{ request.user.cart_set.count }})</a
          >
        </li>
        <li>
          <a href="{% url 'profile' %}">Welcome, {{ request.user.username }}</a>
        </li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'register' %}">Register</a></li>
        {% endif %}
      </nav>
    </header>

    <section class="hero">
      <div class="background-image"></div>
      <div class="hero-content-area">
        {% for product in page %}
        <a href="{% url 'product_detail' product_id=product.id %}">
        <div class="product">
          <img class="product-image" src="{% static 'product_images' %}{{ product.image.url|slice:"28:" }}"
          alt="{{ product.name }}">
          <h3 class="product-name">{{ product.name }}</h3>
          <p class="product-description">{{ product.description }}</p>
          <p class="product-price">Price: ${{ product.price }}</p>
          <p class="product-stock">Stock: {{ product.stock }}</p>
        </a>
          {% if user.is_authenticated %}
          <a class="add-to-cart" href="{% url 'add_to_cart' product.id %}"
            >Add to Cart</a
          ><br>
          <a style="text-decoration: underline;" href="{% url 'product_detail' product_id=product.id %}">Review</a>
          {% else %}
          <a class="add-to-cart" href="{% url 'login' %}">Add to Cart</a>
          {% endif %}
        </div>
        {% endfor %}
        <div style="padding-top: 10px;">
          {% if page.has_previous %}
          <a href="{% url 'product_list' %}?page={{ page.previous_page_number }}" style="color: #00d2ff;">Prev
          </a>
          {% endif %}
          <span>Page {{ page.number }} of {{ page.paginator.num_pages }}</span>
          {% if page.has_next %}
          <a href="{% url 'product_list' %}?page={{ page.next_page_number }}" style="color: #00d2ff;">
              Next
          </a>
          {% endif %}
      </div>
      </div>

      <footer>
        <a href="#">About us</a>
        <a href="#">Support center</a>
        <a href="#">Contact us</a>
        <a href="#">Terms and conditions</a>
      </footer>
    </section>
  </body>
</html>